name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        node: [ '18', '20' ]
    name: CI (Node v${{ matrix.node }})
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm test
